=== rakeshkanchalwar/TestingMirror/com.bitwise.app.product/resources/config/xsds/ComponentConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.bitwise.com/ComponentConfig"
	xmlns:tns="http://www.bitwise.com/ComponentConfig" elementFormDefault="qualified">
	<include schemaLocation=""></include>
	<element name="Config">
		<complexType>
			<sequence>
				<element name="component" type="tns:Component" minOccurs="1"
					maxOccurs="unbounded" />
			</sequence>
		</complexType>
	</element>

	<complexType name="Component">
		<sequence>
			<element name="category" type="tns:category_type" maxOccurs="1" minOccurs="0" />
			<element name="port" type="tns:IOPort" maxOccurs="1" minOccurs="1" />
			<element name="property" type="tns:Property" maxOccurs="unbounded" minOccurs="0" />
			<element name="policy" type="tns:Policy" maxOccurs="unbounded" minOccurs="0" /> 
		</sequence>
		<attribute name="name" type="string" use="required"></attribute>
		<attribute name="nameInPalette" type="string" use="required"></attribute>
		<attribute name="defaultNamePrefix" type="string" use="required"></attribute>
		<attribute name="paletteIconPath" type="string" use="required"></attribute>
		<attribute name="canvasIconPath" type="string" use="required"></attribute>

	</complexType>


	<complexType name="Property">
		<sequence>
			<element name="validation" type="tns:Validation" maxOccurs="unbounded" minOccurs="0"/>
		</sequence>
		<attribute name="type" type="tns:property_type" use="required" />
		<attribute name="renderer" type="tns:property_renderer" use="required" />
		<attribute name="dataType" type="tns:data_type" use="required" />
		<attribute name="name" type="string" use="required" />
		<attribute name="value" type="string" use="optional" />
		<attribute name="group" type="tns:group" use="required" />
		<attribute name="subGroup" type="tns:sub_group" use="required" /> 
		<attribute name="showAsTooltip" type="tns:showAsTooltip" use="required" />
		<attribute name="tooltipDataType" type="tns:tooltipDataType" use="required" />  
		<attribute name="usage" type="tns:usage" use="optional" />  
	</complexType>

	<complexType name="Validation">
		<sequence>
			<element name="expression" type="string" maxOccurs="1" minOccurs="1" />
			<element name="message" type="string" maxOccurs="1" minOccurs="1" />
		</sequence>
	</complexType>

	<complexType name="IOPort">
		<sequence>
		<element name="portSpecification" type="tns:PortSpecification" maxOccurs="unbounded" minOccurs="1"/>
		</sequence>
	</complexType>

 <complexType name="PortSpecification">
		<sequence>
		    <element name="typeOfPort" type="string" maxOccurs="1" minOccurs="1"/>
			<element name="numberOfPorts" type="int" maxOccurs="1" minOccurs="1" />
			<element name="sequenceOfPort" type="int" maxOccurs="1" minOccurs="1" />
			<element name="allowMultipleLinks" type="boolean" maxOccurs="1" minOccurs="0" />
			<element name="linkMandatory" type="boolean" maxOccurs="1" minOccurs="0" />
			<element name="nameOfPort" type="string" maxOccurs="1" minOccurs="1"/>
		</sequence>
	</complexType>
	
	 <complexType name="Policy">
		<sequence>
			<element name="name" type="string" maxOccurs="1" minOccurs="0" />
			<element name="value" type="string" maxOccurs="1" minOccurs="0" />
		</sequence>
	</complexType>

	<simpleType name="property_renderer">
		<restriction base="string">
			<enumeration value="SCHEMA_WIDGET" />
			<enumeration value="FIELD_SEQUENCE_WIDGET" />
			<enumeration value="FIXED_WIDGET"/>
			<enumeration value="RUNTIME_PROPERTIES_WIDGET" />
			<enumeration value="FILE_PATH_WIDGET" />
			<enumeration value="CHARACTER_SET_WIDGET" />
			<enumeration value="DELIMETER_WIDGET" />
			<enumeration value="PHASE_WIDGET" />
			<enumeration value="HAS_HEADER_WIDGET" />
			<enumeration value="SAFE_PROPERTY_WIDGET" />
			<enumeration value="COMPONENT_NAME_WIDGET" />
			<enumeration value="FILTER_PROPERTY_WIDGET" />
			<enumeration value="OPERATIONAL_CLASS_WIDGET" />
			<enumeration value="STRICT_CLASS_WIDGET" />
			<enumeration value="RETENTION_LOGIC_WIDGET"/>
			<enumeration value="COLUMN_NAME_WIDGET"/>
			<enumeration value="CUSTOM_WINDOW_ON_BUTTON_WIDGET"/>
		</restriction>
	</simpleType>

	<simpleType name="usage">
		<restriction base="string">
			<enumeration value="REQUIRED" />
			<enumeration value="OPTIONAL" />
		</restriction>
	</simpleType>
	
	<simpleType name="property_type">
		<restriction base="string">
			<enumeration value="CONFIG" />
			<enumeration value="USER" />
		</restriction>
	</simpleType>
	
	<simpleType name="group">
		<restriction base="string">
			<enumeration value="GENERAL" />
			<enumeration value="SCHEMA" />
			<enumeration value="FIELD_SEQUENCE" />
		</restriction>
	</simpleType>
	
	<simpleType name="sub_group">
		<restriction base="string">
			<enumeration value="DISPLAY" />
			<enumeration value="CONFIGURATION" />
			<enumeration value="RECORD_STRUCTURE_DETAILS" />
		</restriction>
	</simpleType>
	
	<simpleType name="data_type">
		<restriction base="string">
			<enumeration value="string" />
			<enumeration value="boolean" />
		</restriction>
	</simpleType>

	<simpleType name="category_type">
		<restriction base="string">
			<enumeration value="INPUT" />
			<enumeration value="OUTPUT" />
			<enumeration value="TRANSFORM" />
			<enumeration value="STRAIGHTPULL" />
		</restriction>
	</simpleType>
	
	<simpleType name="shape">
		<restriction base="string">
			<enumeration value="InputFigure"/>
			<enumeration value="OutputFigure"/>
			<enumeration value="FilterFigure"/>
			<enumeration value="GatherFigure"/>
			<enumeration value="ReplicateFigure"/>
			<enumeration value="OutputFixedWidthFigure"/>
			<enumeration value="InputFixedWidthFigure"/>
			<enumeration value="DedupFigure"/>
		</restriction>
	</simpleType>
	
	<simpleType name="tooltipDataType">
		<restriction base="string">
			<enumeration value="TEXT"></enumeration>
			<enumeration value="MAP"></enumeration>
			<enumeration value="LIST"></enumeration>
			<enumeration value="LINK"></enumeration>
			<enumeration value="NONE"></enumeration>
		</restriction>
	</simpleType>

	<simpleType name="showAsTooltip">
		<restriction base="string">
			<enumeration value="TRUE"></enumeration>
			<enumeration value="FALSE"></enumeration>
		</restriction>
	</simpleType>
</schema>

=== rakeshkanchalwar/TestingMirror/com.bitwise.app.product/resources/config/gather.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Config xmlns:tns="http://www.bitwise.com/ComponentConfig" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.bitwise.com/ComponentConfig ComponentConfig.xsd ">
  <tns:component paletteIconPath="/icons/gather_palette.png" canvasIconPath="/icons/gather_canvas.png" name="Unionall" nameInPalette="Union All" defaultNamePrefix="Gather">
	<tns:category>STRAIGHTPULL</tns:category>
	<tns:port>
		<tns:portSpecification>
		    <tns:typeOfPort>in</tns:typeOfPort>
		    <tns:numberOfPorts>1</tns:numberOfPorts>
			<tns:sequenceOfPort>1</tns:sequenceOfPort>
			<tns:allowMultipleLinks>true</tns:allowMultipleLinks>
			<tns:linkMandatory>true</tns:linkMandatory>
			<tns:nameOfPort>in0</tns:nameOfPort>
		</tns:portSpecification>
		<tns:portSpecification>
		    <tns:typeOfPort>Out</tns:typeOfPort>
		    <tns:numberOfPorts>1</tns:numberOfPorts>
			<tns:sequenceOfPort>1</tns:sequenceOfPort>
			<tns:allowMultipleLinks>false</tns:allowMultipleLinks>
			<tns:linkMandatory>true</tns:linkMandatory>
			<tns:nameOfPort>out0</tns:nameOfPort>
		</tns:portSpecification>
	</tns:port>
	<tns:property dataType="string" name="name" renderer="COMPONENT_NAME_WIDGET" 
		type="USER" group="GENERAL" subGroup="DISPLAY" showAsTooltip="TRUE" tooltipDataType="TEXT"/>
		
	<tns:property dataType="string" name="phase" value="0" renderer="PHASE_WIDGET"
		 type="USER" group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="TRUE" tooltipDataType="TEXT"/>
		 
	 <tns:property dataType="string" name="runtime_properties" renderer="RUNTIME_PROPERTIES_WIDGET" 
	 	type="USER" group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="FALSE" tooltipDataType="NONE" />
  </tns:component>
</tns:Config>

=== rakeshkanchalwar/TestingMirror/com.bitwise.app.product/resources/config/dedup.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Config xmlns:tns="http://www.bitwise.com/ComponentConfig"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.bitwise.com/ComponentConfig ComponentConfig.xsd ">
	<tns:component paletteIconPath="/icons/dedup_palette.png" canvasIconPath="/icons/dedup_canvas.png" name="Dedup"
		shape="DedupFigure">
		<tns:category>STRAIGHTPULL</tns:category>
		<tns:port>
			<tns:portSpecification>
				<tns:typeOfPort>in</tns:typeOfPort>
				<tns:numberOfPorts>1</tns:numberOfPorts>
				<tns:sequenceOfPort>1</tns:sequenceOfPort>
				<tns:allowMultipleLinks>false</tns:allowMultipleLinks>
				<tns:linkMandatory>true</tns:linkMandatory>
				<tns:nameOfPort>in0</tns:nameOfPort>
			</tns:portSpecification>
			<tns:portSpecification>
				<tns:typeOfPort>out</tns:typeOfPort>
				<tns:numberOfPorts>2</tns:numberOfPorts>
				<tns:sequenceOfPort>1</tns:sequenceOfPort>
				<tns:allowMultipleLinks>false</tns:allowMultipleLinks>
				<tns:linkMandatory>true</tns:linkMandatory>
				<tns:nameOfPort>out0</tns:nameOfPort>
			</tns:portSpecification>
			<tns:portSpecification>
				<tns:typeOfPort>out</tns:typeOfPort>
				<tns:numberOfPorts>2</tns:numberOfPorts>
				<tns:sequenceOfPort>2</tns:sequenceOfPort>
				<tns:allowMultipleLinks>false</tns:allowMultipleLinks>
				<tns:linkMandatory>false</tns:linkMandatory>
				<tns:nameOfPort>unused0</tns:nameOfPort>
			</tns:portSpecification>
		</tns:port>
		<tns:property dataType="string" name="name"
			renderer="COMPONENT_NAME_WIDGET" type="USER" group="GENERAL"
			subGroup="DISPLAY" showAsTooltip="TRUE" tooltipDataType="TEXT" />
			
		<tns:property dataType="string" name="phase" value="0" renderer="PHASE_WIDGET"
			type="USER" group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="TRUE" tooltipDataType="TEXT" />
			
		<tns:property dataType="string" name="runtime_properties" renderer="RUNTIME_PROPERTIES_WIDGET" 
		    type="USER" group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="FALSE" tooltipDataType="NONE" />
				
		<tns:property dataType="string" name="COLUMN_NAME" renderer="COLUMN_NAME_WIDGET"
		 type="USER" group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="TRUE" tooltipDataType="LIST"/>
 		
 		<tns:property dataType="string" group="GENERAL" subGroup="CONFIGURATION" name="retention_logic"
 		    value="First" renderer="RETENTION_LOGIC_WIDGET" type="USER" showAsTooltip="TRUE" tooltipDataType="TEXT" />
	</tns:component>
</tns:Config>

=== rakeshkanchalwar/TestingMirror/com.bitwise.app.product/resources/config/inputfixedwidth.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Config xmlns:tns="http://www.bitwise.com/ComponentConfig" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.bitwise.com/ComponentConfig ComponentConfig.xsd ">
	<tns:component paletteIconPath="/icons/input_palette.png" canvasIconPath="/icons/input_canvas.png"
		name="IFixedWidth" nameInPalette="File Fixed Width" defaultNamePrefix="IFixedWidth">
		<tns:category>INPUT</tns:category>
		<tns:port>
			<tns:portSpecification>
				<tns:typeOfPort>out</tns:typeOfPort>
				<tns:numberOfPorts>1</tns:numberOfPorts>
				<tns:sequenceOfPort>1</tns:sequenceOfPort>
				<tns:allowMultipleLinks>false</tns:allowMultipleLinks>
				<tns:linkMandatory>true</tns:linkMandatory>
				<tns:nameOfPort>out0</tns:nameOfPort>
			</tns:portSpecification>
			
		</tns:port>
		<tns:property dataType="string" name="name" renderer="COMPONENT_NAME_WIDGET" type="USER"
			group="GENERAL" subGroup="DISPLAY" showAsTooltip="TRUE" tooltipDataType="TEXT"
			usage="REQUIRED"/>
		
		<tns:property dataType="string" name="schema" renderer="FIXED_WIDGET" type="USER"
			group="SCHEMA" subGroup="RECORD_STRUCTURE_DETAILS" showAsTooltip="FALSE" tooltipDataType="NONE"
			usage="REQUIRED"/>
		
		<tns:property dataType="string" name="path" renderer="FILE_PATH_WIDGET" type="USER"
			group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="TRUE" tooltipDataType="LINK"
			usage="REQUIRED"/>
		
		<tns:property dataType="string" group="GENERAL" subGroup="CONFIGURATION" name="strict"
		renderer="STRICT_CLASS_WIDGET" type="USER" showAsTooltip="FALSE" tooltipDataType="NONE"
		usage="OPTIONAL"/>
		
		<tns:property dataType="boolean" name="safe" renderer="SAFE_PROPERTY_WIDGET" type="USER"
			group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="FALSE" tooltipDataType="NONE"
			usage="OPTIONAL"/>
		
		<tns:property dataType="string" name="charset" value="UTF-8" renderer="CHARACTER_SET_WIDGET"
			type="USER" group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="FALSE" tooltipDataType="NONE"
			usage="REQUIRED"/>
		
		<tns:property dataType="string" name="runtime_properties" renderer="RUNTIME_PROPERTIES_WIDGET"
			type="USER" group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="FALSE" tooltipDataType="NONE"
			usage="OPTIONAL"/>
		
		<tns:property dataType="string" name="phase" value="0" renderer="PHASE_WIDGET" type="USER"
			group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="TRUE" tooltipDataType="TEXT"
			usage="REQUIRED"/>
	</tns:component>
</tns:Config>

=== rakeshkanchalwar/TestingMirror/com.bitwise.app.product/resources/config/outputfixedwidth.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Config xmlns:tns="http://www.bitwise.com/ComponentConfig" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.bitwise.com/ComponentConfig ComponentConfig.xsd ">
  <tns:component paletteIconPath="/icons/output_palette.png" canvasIconPath="/icons/output_canvas.png" name="OFixedWidth" nameInPalette="File Fixed Width" defaultNamePrefix="OFixedWidth">
    <tns:category>OUTPUT</tns:category>
 <tns:port>
		<tns:portSpecification>
		    <tns:typeOfPort>in</tns:typeOfPort>
		    <tns:numberOfPorts>1</tns:numberOfPorts>
			<tns:sequenceOfPort>1</tns:sequenceOfPort>
			<tns:allowMultipleLinks>false</tns:allowMultipleLinks>
			<tns:linkMandatory>true</tns:linkMandatory>
			<tns:nameOfPort>in0</tns:nameOfPort>
		</tns:portSpecification>
		
	</tns:port>
    <tns:property dataType="string" name="name" renderer="COMPONENT_NAME_WIDGET" type="USER" group="GENERAL" 
    	subGroup="DISPLAY" showAsTooltip="TRUE" tooltipDataType="TEXT"/>
    	
    <tns:property dataType="string" name="schema" renderer="FIXED_WIDGET" type="USER" group="SCHEMA" 
    	subGroup="RECORD_STRUCTURE_DETAILS" showAsTooltip="FALSE" tooltipDataType="NONE"/>
    	
    <tns:property dataType="string" name="path" renderer="FILE_PATH_WIDGET" type="USER" group="GENERAL" 
    	subGroup="CONFIGURATION" showAsTooltip="TRUE" tooltipDataType="LINK"/>
    	
    <tns:property dataType="string" group="GENERAL" subGroup="CONFIGURATION" name="strict"
    	renderer="STRICT_CLASS_WIDGET" type="USER" showAsTooltip="FALSE" tooltipDataType="NONE" />
    	
    <tns:property dataType="boolean" name="safe" renderer="SAFE_PROPERTY_WIDGET" type="USER" group="GENERAL" 
    	subGroup="CONFIGURATION" showAsTooltip="FALSE" tooltipDataType="NONE" />
    	
  <tns:property dataType="string" name="charset" value="UTF-8" renderer="CHARACTER_SET_WIDGET" type="USER" 
    	group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="FALSE" tooltipDataType="NONE" />
    	
    <tns:property dataType="string" name="runtime_properties" renderer="RUNTIME_PROPERTIES_WIDGET" type="USER" 
    	group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="FALSE" tooltipDataType="NONE" />
    	
    <tns:property dataType="string" name="phase" value="0" renderer="PHASE_WIDGET" type="USER" group="GENERAL"
    	 subGroup="CONFIGURATION" showAsTooltip="TRUE" tooltipDataType="TEXT" />
  </tns:component>
</tns:Config>

=== rakeshkanchalwar/TestingMirror/com.bitwise.app.product/resources/config/outputdelimited.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Config xmlns:tns="http://www.bitwise.com/ComponentConfig" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.bitwise.com/ComponentConfig ComponentConfig.xsd ">
  <tns:component paletteIconPath="/icons/output_palette.png" canvasIconPath="/icons/output_canvas.png" name="OFDelimited" nameInPalette="File Delimited" defaultNamePrefix="ODelimited">
    <tns:category>OUTPUT</tns:category>
 <tns:port>
		<tns:portSpecification>
		    <tns:typeOfPort>in</tns:typeOfPort>
		    <tns:numberOfPorts>1</tns:numberOfPorts>
			<tns:sequenceOfPort>1</tns:sequenceOfPort>
			<tns:allowMultipleLinks>false</tns:allowMultipleLinks>
			<tns:linkMandatory>true</tns:linkMandatory>
		    <tns:nameOfPort>in0</tns:nameOfPort>
			
		</tns:portSpecification>
		
	</tns:port>
    <tns:property dataType="string" name="name" renderer="COMPONENT_NAME_WIDGET" 
    	type="USER" group="GENERAL" subGroup="DISPLAY" showAsTooltip="TRUE" tooltipDataType="TEXT"/>
    	
    <tns:property dataType="string" group="FIELD_SEQUENCE" subGroup="RECORD_STRUCTURE_DETAILS"
    	 name="schema" renderer="FIELD_SEQUENCE_WIDGET" type="USER" showAsTooltip="FALSE" tooltipDataType="NONE"/>
    	 
    <tns:property dataType="string" group="GENERAL" subGroup="CONFIGURATION" name="path"
    	renderer="FILE_PATH_WIDGET" type="USER" showAsTooltip="TRUE" tooltipDataType="LINK" />
    	
    <tns:property dataType="string" group="GENERAL" subGroup="CONFIGURATION" name="delimiter" value="|"
    	renderer="DELIMETER_WIDGET" type="USER" showAsTooltip="TRUE" tooltipDataType="TEXT"/>
    	
    <tns:property dataType="boolean" group="GENERAL" subGroup="CONFIGURATION" name="HAS_HEADER_WIDGET"
    	renderer="HAS_HEADER_WIDGET" type="USER" showAsTooltip="FALSE" tooltipDataType="NONE"/>
    	
    <tns:property dataType="string" group="GENERAL" subGroup="CONFIGURATION" name="charset" value="UTF-8"
    	renderer="CHARACTER_SET_WIDGET" type="USER" showAsTooltip="FALSE" tooltipDataType="NONE"/>
    	
    <tns:property dataType="string" group="GENERAL" subGroup="CONFIGURATION" name="runtime_properties"
    	renderer="RUNTIME_PROPERTIES_WIDGET" type="USER" showAsTooltip="FALSE" tooltipDataType="NONE"/>
    	
    <tns:property dataType="string" name="phase" value="0" renderer="PHASE_WIDGET" type="USER" 
    	group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="TRUE" tooltipDataType="TEXT"/>
  </tns:component>
</tns:Config>

=== rakeshkanchalwar/TestingMirror/com.bitwise.app.product/resources/config/output.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Config xmlns:tns="http://www.bitwise.com/ComponentConfig" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.bitwise.com/ComponentConfig ComponentConfig.xsd ">
  <tns:component iconPath="/icons/output.png" name="Output" shape="OutputFigure">
    <tns:category>OUTPUT</tns:category>
    <tns:inputPort>
      <tns:numberOfPorts>1</tns:numberOfPorts>
      <tns:allowMultipleLinks>false</tns:allowMultipleLinks>
    </tns:inputPort>
    <tns:outputPort>
      <tns:numberOfPorts>0</tns:numberOfPorts>
    </tns:outputPort>
    <tns:property dataType="string" name="name" renderer="ELTComponentNameWidget" type="USER" group="GENERAL" subGroup="NAME"/>
    <tns:property dataType="string" group="FIELD_SEQUENCE" subGroup="FIELD_SEQUENCE" name="field_sequence" renderer="ELTFieldSequenceWidget" type="USER" />
    <tns:property dataType="string" group="GENERAL" subGroup="FILE_PATH" name="path" renderer="ELTFilePathWidget" type="USER"/>
    <tns:property dataType="string" group="GENERAL" subGroup="DELIMITER" name="delimiter" renderer="ELTDelimeterWidget" type="USER"/>
    <tns:property dataType="boolean" group="GENERAL" subGroup="HEADER" name="has_header" renderer="ELTHasHeaderWidget" type="USER"/>
    <tns:property dataType="string" group="GENERAL" subGroup="CHARSET" name="charset" renderer="ELTCharacterSetWidget" type="USER"/>
    <tns:property dataType="string" group="RUNTIME_PROPERTIES" subGroup="RUNTIME_PROPERTIES" name="runtime_properties" renderer="ELTRuntimePropertiesWidget" type="USER"/>
    <tns:property dataType="string" name="phase" renderer="ELTPhaseWidget" type="USER" group="GENERAL" subGroup="PHASE" />
  </tns:component>
</tns:Config>

=== rakeshkanchalwar/TestingMirror/com.bitwise.app.product/resources/config/aggregate.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Config xmlns:tns="http://www.bitwise.com/ComponentConfig" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.bitwise.com/ComponentConfig ComponentConfig.xsd ">
	<tns:component paletteIconPath="/icons/aggregate_palette.png" canvasIconPath="/icons/aggregate_canvas.png"
		name="Aggregate" nameInPalette="Aggregate" defaultNamePrefix="Aggregate">
		<tns:category>TRANSFORM</tns:category>
		<tns:port>
			<tns:portSpecification>
				<tns:typeOfPort>in</tns:typeOfPort>
				<tns:numberOfPorts>1</tns:numberOfPorts>
				<tns:sequenceOfPort>1</tns:sequenceOfPort>
				<tns:allowMultipleLinks>false</tns:allowMultipleLinks>
				<tns:linkMandatory>true</tns:linkMandatory>
				<tns:nameOfPort>in0</tns:nameOfPort>
			</tns:portSpecification>
			<tns:portSpecification>
				<tns:typeOfPort>out</tns:typeOfPort>
				<tns:numberOfPorts>1</tns:numberOfPorts>
				<tns:sequenceOfPort>1</tns:sequenceOfPort>
				<tns:allowMultipleLinks>false</tns:allowMultipleLinks>
				<tns:linkMandatory>true</tns:linkMandatory>
				<tns:nameOfPort>out0</tns:nameOfPort>
			</tns:portSpecification>
		</tns:port>
		<tns:property dataType="string" name="name" renderer="COMPONENT_NAME_WIDGET" type="USER"
			group="GENERAL" subGroup="DISPLAY" showAsTooltip="TRUE" tooltipDataType="TEXT"/>
		<tns:property dataType="string" name="runtime_properties" renderer="CUSTOM_WINDOW_ON_BUTTON_WIDGET"
			type="USER" group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="FALSE" tooltipDataType="NONE"/>
		<tns:property dataType="string" name="phase" value="0" renderer="PHASE_WIDGET" type="USER"
			group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="TRUE" tooltipDataType="TEXT"/>
		
		
	</tns:component>
</tns:Config>

=== rakeshkanchalwar/TestingMirror/com.bitwise.app.product/resources/config/input.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Config xmlns:tns="http://www.bitwise.com/ComponentConfig" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.bitwise.com/ComponentConfig ComponentConfig.xsd ">
  <tns:component iconPath="/icons/input.png" name="Input" shape="InputFigure">
	<tns:category>INPUT</tns:category>
	<tns:inputPort>
		<tns:numberOfPorts>0</tns:numberOfPorts>
	</tns:inputPort>
	<tns:outputPort>
		<tns:numberOfPorts>1</tns:numberOfPorts>
		<tns:allowMultipleLinks>false</tns:allowMultipleLinks>
	</tns:outputPort>
	<tns:property dataType="string" name="name" renderer="ELTComponentNameWidget" type="USER" group="GENERAL" subGroup="NAME"/>
    <tns:property dataType="string" name="schema" renderer="ELTSchemaWidget" type="USER" group="SCHEMA" subGroup="SCHEMA"/>
    <tns:property dataType="string" name="path" renderer="ELTFilePathWidget" type="USER" group="GENERAL" subGroup="FILE_PATH"/>
    <tns:property dataType="string" name="delimiter" renderer="ELTDelimeterWidget" type="USER" group="GENERAL" subGroup="DELIMITER"/>
    <tns:property dataType="boolean" name="safe" renderer="ELTSafePropertyWidget" type="USER" group="GENERAL" subGroup="SAFE"/>
    <tns:property dataType="boolean" name="has_header" renderer="ELTHasHeaderWidget" type="USER" group="GENERAL" subGroup="HEADER"/>
    <tns:property dataType="string" name="charset" renderer="ELTCharacterSetWidget" type="USER" group="GENERAL" subGroup="CHARSET"/>
    <tns:property dataType="string" name="runtime_properties" renderer="ELTRuntimePropertiesWidget" type="USER" group="RUNTIME_PROPERTIES" subGroup="RUNTIME_PROPERTIES"/>
    <tns:property dataType="string" name="phase" renderer="ELTPhaseWidget" type="USER" group="GENERAL" subGroup="PHASE"/>
  </tns:component>
</tns:Config>
