=== rakeshkanchalwar/TestingMirror/com.bitwise.app.product/resources/config/xsds/ComponentConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.bitwise.com/ComponentConfig"
	xmlns:tns="http://www.bitwise.com/ComponentConfig" elementFormDefault="qualified">
	<include schemaLocation=""></include>
	<element name="Config">
		<complexType>
			<sequence>
				<element name="component" type="tns:Component" minOccurs="1"
					maxOccurs="unbounded" />
			</sequence>
		</complexType>
	</element>

	<complexType name="Component">
		<sequence>
			<element name="category" type="tns:category_type" maxOccurs="1" minOccurs="0" />
			<element name="port" type="tns:IOPort" maxOccurs="1" minOccurs="1" />
			<element name="property" type="tns:Property" maxOccurs="unbounded" minOccurs="0" />
			<element name="policy" type="tns:Policy" maxOccurs="unbounded" minOccurs="0" /> 
		</sequence>
		<attribute name="name" type="string" use="required"></attribute>
		<attribute name="nameInPalette" type="string" use="required"></attribute>
		<attribute name="defaultNamePrefix" type="string" use="required"></attribute>
		<attribute name="paletteIconPath" type="string" use="required"></attribute>
		<attribute name="canvasIconPath" type="string" use="required"></attribute>

	</complexType>


	<complexType name="Property">
		<sequence>
			<element name="validation" type="tns:Validation" maxOccurs="unbounded" minOccurs="0"/>
		</sequence>
		<attribute name="type" type="tns:property_type" use="required" />
		<attribute name="renderer" type="tns:property_renderer" use="required" />
		<attribute name="dataType" type="tns:data_type" use="required" />
		<attribute name="name" type="string" use="required" />
		<attribute name="value" type="string" use="optional" />
		<attribute name="group" type="tns:group" use="required" />
		<attribute name="subGroup" type="tns:sub_group" use="required" /> 
		<attribute name="showAsTooltip" type="tns:showAsTooltip" use="required" />
		<attribute name="tooltipDataType" type="tns:tooltipDataType" use="required" />  
		<attribute name="usage" type="tns:usage" use="optional" />  
	</complexType>

	<complexType name="Validation">
		<sequence>
			<element name="expression" type="string" maxOccurs="1" minOccurs="1" />
			<element name="message" type="string" maxOccurs="1" minOccurs="1" />
		</sequence>
	</complexType>

	<complexType name="IOPort">
		<sequence>
		<element name="portSpecification" type="tns:PortSpecification" maxOccurs="unbounded" minOccurs="1"/>
		</sequence>
	</complexType>

 <complexType name="PortSpecification">
		<sequence>
		    <element name="typeOfPort" type="string" maxOccurs="1" minOccurs="1"/>
			<element name="numberOfPorts" type="int" maxOccurs="1" minOccurs="1" />
			<element name="sequenceOfPort" type="int" maxOccurs="1" minOccurs="1" />
			<element name="allowMultipleLinks" type="boolean" maxOccurs="1" minOccurs="0" />
			<element name="linkMandatory" type="boolean" maxOccurs="1" minOccurs="0" />
			<element name="nameOfPort" type="string" maxOccurs="1" minOccurs="1"/>
		</sequence>
	</complexType>
	
	 <complexType name="Policy">
		<sequence>
			<element name="name" type="string" maxOccurs="1" minOccurs="0" />
			<element name="value" type="string" maxOccurs="1" minOccurs="0" />
		</sequence>
	</complexType>

	<simpleType name="property_renderer">
		<restriction base="string">
			<enumeration value="SCHEMA_WIDGET" />
			<enumeration value="FIELD_SEQUENCE_WIDGET" />
			<enumeration value="FIXED_WIDGET"/>
			<enumeration value="RUNTIME_PROPERTIES_WIDGET" />
			<enumeration value="FILE_PATH_WIDGET" />
			<enumeration value="CHARACTER_SET_WIDGET" />
			<enumeration value="DELIMETER_WIDGET" />
			<enumeration value="PHASE_WIDGET" />
			<enumeration value="HAS_HEADER_WIDGET" />
			<enumeration value="SAFE_PROPERTY_WIDGET" />
			<enumeration value="COMPONENT_NAME_WIDGET" />
			<enumeration value="FILTER_PROPERTY_WIDGET" />
			<enumeration value="OPERATIONAL_CLASS_WIDGET" />
			<enumeration value="STRICT_CLASS_WIDGET" />
			<enumeration value="RETENTION_LOGIC_WIDGET"/>
			<enumeration value="COLUMN_NAME_WIDGET"/>
			<enumeration value="CUSTOM_WINDOW_ON_BUTTON_WIDGET"/>
		</restriction>
	</simpleType>

	<simpleType name="usage">
		<restriction base="string">
			<enumeration value="REQUIRED" />
			<enumeration value="OPTIONAL" />
		</restriction>
	</simpleType>
	
	<simpleType name="property_type">
		<restriction base="string">
			<enumeration value="CONFIG" />
			<enumeration value="USER" />
		</restriction>
	</simpleType>
	
	<simpleType name="group">
		<restriction base="string">
			<enumeration value="GENERAL" />
			<enumeration value="SCHEMA" />
			<enumeration value="FIELD_SEQUENCE" />
		</restriction>
	</simpleType>
	
	<simpleType name="sub_group">
		<restriction base="string">
			<enumeration value="DISPLAY" />
			<enumeration value="CONFIGURATION" />
			<enumeration value="RECORD_STRUCTURE_DETAILS" />
		</restriction>
	</simpleType>
	
	<simpleType name="data_type">
		<restriction base="string">
			<enumeration value="string" />
			<enumeration value="boolean" />
		</restriction>
	</simpleType>

	<simpleType name="category_type">
		<restriction base="string">
			<enumeration value="INPUT" />
			<enumeration value="OUTPUT" />
			<enumeration value="TRANSFORM" />
			<enumeration value="STRAIGHTPULL" />
		</restriction>
	</simpleType>
	
	<simpleType name="shape">
		<restriction base="string">
			<enumeration value="InputFigure"/>
			<enumeration value="OutputFigure"/>
			<enumeration value="FilterFigure"/>
			<enumeration value="GatherFigure"/>
			<enumeration value="ReplicateFigure"/>
			<enumeration value="OutputFixedWidthFigure"/>
			<enumeration value="InputFixedWidthFigure"/>
			<enumeration value="DedupFigure"/>
		</restriction>
	</simpleType>
	
	<simpleType name="tooltipDataType">
		<restriction base="string">
			<enumeration value="TEXT"></enumeration>
			<enumeration value="MAP"></enumeration>
			<enumeration value="LIST"></enumeration>
			<enumeration value="LINK"></enumeration>
			<enumeration value="NONE"></enumeration>
		</restriction>
	</simpleType>

	<simpleType name="showAsTooltip">
		<restriction base="string">
			<enumeration value="TRUE"></enumeration>
			<enumeration value="FALSE"></enumeration>
		</restriction>
	</simpleType>
</schema>

=== rakeshkanchalwar/TestingMirror/com.bitwise.app.product/resources/config/filter.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Config xmlns:tns="http://www.bitwise.com/ComponentConfig"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.bitwise.com/ComponentConfig ComponentConfig.xsd ">
	<tns:component paletteIconPath="/icons/filter_palette.png" canvasIconPath="/icons/filter_canvas.png" name="Filter"
		nameInPalette="Filter" defaultNamePrefix="Filter">
		<tns:category>TRANSFORM</tns:category>
		<tns:port>
			<tns:portSpecification>
				<tns:typeOfPort>in</tns:typeOfPort>
				<tns:numberOfPorts>1</tns:numberOfPorts>
				<tns:sequenceOfPort>1</tns:sequenceOfPort>
				<tns:allowMultipleLinks>false</tns:allowMultipleLinks>
				<tns:linkMandatory>true</tns:linkMandatory>
				<tns:nameOfPort>in0</tns:nameOfPort>
				
			</tns:portSpecification>
			<tns:portSpecification>
				<tns:typeOfPort>out</tns:typeOfPort>
				<tns:numberOfPorts>2</tns:numberOfPorts>
				<tns:sequenceOfPort>1</tns:sequenceOfPort>
				<tns:allowMultipleLinks>false</tns:allowMultipleLinks>
				<tns:linkMandatory>true</tns:linkMandatory>
				<tns:nameOfPort>out0</tns:nameOfPort>
			</tns:portSpecification>
			<tns:portSpecification>
				<tns:typeOfPort>out</tns:typeOfPort>
				<tns:numberOfPorts>2</tns:numberOfPorts>
				<tns:sequenceOfPort>2</tns:sequenceOfPort>
				<tns:allowMultipleLinks>false</tns:allowMultipleLinks>
				<tns:linkMandatory>false</tns:linkMandatory>
				<tns:nameOfPort>unused0</tns:nameOfPort>
			</tns:portSpecification>
		</tns:port>
		
		<tns:property dataType="string" name="name"
			renderer="COMPONENT_NAME_WIDGET" type="USER" group="GENERAL"
			subGroup="DISPLAY" showAsTooltip="TRUE" tooltipDataType="TEXT" />
			
		<tns:property dataType="string" name="phase" value="0" renderer="PHASE_WIDGET"
			type="USER" group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="TRUE" tooltipDataType="TEXT" />
			
		<tns:property dataType="string" name="oprationClass"
			renderer="OPERATIONAL_CLASS_WIDGET" type="USER" group="GENERAL"
			subGroup="CONFIGURATION" showAsTooltip="TRUE" tooltipDataType="LINK" />
			
		<tns:property dataType="string" name="filter" renderer="FILTER_PROPERTY_WIDGET" 
		    type="USER" group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="TRUE" tooltipDataType="LIST" />
		    
	</tns:component>
</tns:Config>

=== rakeshkanchalwar/TestingMirror/com.bitwise.app.product/resources/config/transform.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Config xmlns:tns="http://www.bitwise.com/ComponentConfig" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.bitwise.com/ComponentConfig ComponentConfig.xsd ">
	<tns:component paletteIconPath="/icons/transform_palette.png" canvasIconPath="/icons/transform_canvas.png"
		name="Transform" nameInPalette="Transform" defaultNamePrefix="Transform">
		<tns:category>TRANSFORM</tns:category>
		<tns:port>
			<tns:portSpecification>
				<tns:typeOfPort>in</tns:typeOfPort>
				<tns:numberOfPorts>1</tns:numberOfPorts>
				<tns:sequenceOfPort>1</tns:sequenceOfPort>
				<tns:allowMultipleLinks>false</tns:allowMultipleLinks>
				<tns:linkMandatory>true</tns:linkMandatory>
				<tns:nameOfPort>in0</tns:nameOfPort>
			</tns:portSpecification>
			<tns:portSpecification>
				<tns:typeOfPort>out</tns:typeOfPort>
				<tns:numberOfPorts>1</tns:numberOfPorts>
				<tns:sequenceOfPort>1</tns:sequenceOfPort>
				<tns:allowMultipleLinks>false</tns:allowMultipleLinks>
				<tns:linkMandatory>true</tns:linkMandatory>
				<tns:nameOfPort>out0</tns:nameOfPort>
			</tns:portSpecification>
		</tns:port>
		<tns:property dataType="string" name="name" renderer="COMPONENT_NAME_WIDGET" type="USER"
			group="GENERAL" subGroup="DISPLAY" showAsTooltip="TRUE" tooltipDataType="TEXT"
			usage="REQUIRED"/>
		
		<tns:property dataType="string" name="runtime_properties" renderer="RUNTIME_PROPERTIES_WIDGET"
			type="USER" group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="FALSE" tooltipDataType="NONE"
			usage="OPTIONAL"/>
				
		<tns:property dataType="string" name="phase" value="0" renderer="PHASE_WIDGET" type="USER"
			group="GENERAL" subGroup="CONFIGURATION" showAsTooltip="TRUE" tooltipDataType="TEXT"
			usage="REQUIRED"/>
	</tns:component>
</tns:Config>

=== rakeshkanchalwar/TestingMirror/com.bitwise.app.product/resources/config/replicate.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Config xmlns:tns="http://www.bitwise.com/ComponentConfig" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.bitwise.com/ComponentConfig ComponentConfig.xsd ">
  <tns:component iconPath="/icons/output.png" name="Replicate" shape="ReplicateFigure">
	<tns:category>STRAIGHTPULL</tns:category>
	<tns:inputPort>
		<tns:numberOfPorts>1</tns:numberOfPorts>
	</tns:inputPort>
	<tns:outputPort>
		<tns:numberOfPorts>1</tns:numberOfPorts>
		<tns:allowMultipleLinks>true</tns:allowMultipleLinks>
	</tns:outputPort>
	<tns:property dataType="string" name="name" renderer="ELTComponentNameWidget" type="USER" group="GENERAL" subGroup="NAME"/>
	 <tns:property dataType="string" name="phase" renderer="ELTPhaseWidget" type="USER" group="GENERAL" subGroup="PHASE" />
	</tns:component>
</tns:Config>
