=== rakeshkanchalwar/TestingMirror/com.bitwise.app.common/bin/target/classes/resources/ComponentConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.bitwise.com/ComponentConfig"
	xmlns:tns="http://www.bitwise.com/ComponentConfig" elementFormDefault="qualified">
	<include schemaLocation=""></include>
	<element name="Config">
		<complexType>
			<sequence>
				<element name="component" type="tns:Component" minOccurs="1"
					maxOccurs="unbounded" />
			</sequence>
		</complexType>
	</element>

	<complexType name="Component">
		<sequence>
			<element name="name" type="string" maxOccurs="1" minOccurs="1" />
			<element name="category" type="tns:category_type" maxOccurs="1"
				minOccurs="0"></element>
			<element name="defaultNamePrefix" type="string" maxOccurs="1"
				minOccurs="1" />
			<element name="iconPath" type="string" maxOccurs="1"
				minOccurs="1" />
			<element name="inputPort" type="tns:IOPort" maxOccurs="1"
				minOccurs="0" />
			<element name="outputPort" type="tns:IOPort" maxOccurs="1"
				minOccurs="0" />
			<element name="property" type="tns:Property" maxOccurs="unbounded"
				minOccurs="0" />
			<element name="properties" type="tns:Properties" maxOccurs="1"
				minOccurs="0" />
			<element name="policy" type="tns:Policy" maxOccurs="unbounded"
				minOccurs="0"></element>
		</sequence>
	</complexType>

	<complexType name="Properties">
		<sequence>
			<element name="property" type="tns:Property" maxOccurs="unbounded"
				minOccurs="0" />
			<element name="properties" type="tns:Properties" maxOccurs="1"
				minOccurs="0" />
		</sequence>
	</complexType>

	<complexType name="Property">
		<sequence>
			<element name="type" type="tns:property_type" maxOccurs="1"
				minOccurs="1" />
			<element name="renderer" type="tns:property_renderer"
				maxOccurs="1" minOccurs="1" />
			<element name="name" type="string" maxOccurs="1" minOccurs="1" />
			<element name="value" type="string" maxOccurs="1" minOccurs="1" />
			<element name="validation" type="tns:Validation" maxOccurs="unbounded"
				minOccurs="0" />
		</sequence>
	</complexType>

	<complexType name="Validation">
		<sequence>
			<element name="expression" type="string" maxOccurs="1"
				minOccurs="1" />
			<element name="message" type="string" maxOccurs="1"
				minOccurs="1" />
		</sequence>
	</complexType>

	<complexType name="IOPort">
		<sequence>
			<element name="numberOfPorts" type="integer" maxOccurs="1"
				minOccurs="1" />
		</sequence>
	</complexType>

	<complexType name="Policy">
		<sequence>
			<element name="name" type="string" maxOccurs="1" minOccurs="0" />
			<element name="value" type="string" maxOccurs="1" minOccurs="0" />
		</sequence>
	</complexType>

	<simpleType name="property_renderer">
		<restriction base="string">
			<enumeration value="FILE" />
			<enumeration value="TEXT" />
		</restriction>
	</simpleType>

	<simpleType name="property_type">
		<restriction base="string">
			<enumeration value="CONFIG" />
			<enumeration value="USER" />
		</restriction>
	</simpleType>

	<simpleType name="category_type">
		<restriction base="string">
			<enumeration value="INPUT" />
			<enumeration value="OUTPUT" />
		</restriction>
	</simpleType>
</schema>

=== rakeshkanchalwar/TestingMirror/com.bitwise.app.common/NewFile.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Config xmlns:tns="http://www.bitwise.com/ComponentConfig"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.bitwise.com/ComponentConfig src/resources/ComponentConfig.xsd ">
	<tns:component>
		<tns:name>Input</tns:name>
		<tns:defaultNamePrefix>defaultNamePrefix</tns:defaultNamePrefix>
		<tns:iconPath>icon/InputFile.png</tns:iconPath>
		<tns:property>
			<tns:name>Name</tns:name>
			<tns:value>Input</tns:value>
		</tns:property>
		<tns:property>
			<tns:name>Output</tns:name>
			<tns:value>text file</tns:value>
		</tns:property>
	</tns:component>
</tns:Config>
