=== rakeshkanchalwar/TestingMirror/com.bitwise.app.common/src/resources/ComponentConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.bitwise.com/ComponentConfig"
	xmlns:tns="http://www.bitwise.com/ComponentConfig" elementFormDefault="qualified">
    <include schemaLocation=""></include>
    <element name="Config">
		<complexType>
			<sequence>
				<element name="component" type="tns:Component" minOccurs="1"
					maxOccurs="unbounded" />
			</sequence>
		</complexType>
	</element>

	<complexType name="Component">
		<sequence>
			<element name="name" type="string" maxOccurs="1"
				minOccurs="1" />
			<element name="defaultNamePrefix" type="string"
				maxOccurs="1" minOccurs="1" />
			<element name="iconPath" type="string" maxOccurs="1"
				minOccurs="1" />
			<element name="inputPort" type="tns:IOPort" maxOccurs="1"
				minOccurs="0" />
			<element name="outputPort" type="tns:IOPort" maxOccurs="1"
				minOccurs="0" />
			<element name="property" type="tns:Property"
				maxOccurs="unbounded" minOccurs="0" />
			<element name="properties" type="tns:Properties"
				maxOccurs="1" minOccurs="0" />
			<element name="policies" type="tns:Policies" maxOccurs="unbounded" minOccurs="0"></element>
		</sequence>
	</complexType>

	<complexType name="Properties">
		<sequence>
			<element name="property" type="tns:Property" maxOccurs="unbounded" minOccurs="0"/>
			<element name="properties" type="tns:Properties" maxOccurs="1" minOccurs="0"/>
		</sequence>
	</complexType>

	<complexType name="Property">
		<sequence>
			<element name="name" type="string" maxOccurs="1" minOccurs="1" />
			<element name="value" type="string" maxOccurs="1" minOccurs="1" />
			<element name="validation" type="tns:Validation" maxOccurs="unbounded"
				minOccurs="0" />
		</sequence>
	</complexType>

	<complexType name="Validation">
		<sequence>
			<element name="expression" type="string" maxOccurs="1"
				minOccurs="1" />
			<element name="message" type="string" maxOccurs="1"
				minOccurs="1" />
		</sequence>
	</complexType>

	<complexType name="IOPort">
		<sequence>
			<element name="numberOfPorts" type="integer" maxOccurs="1"
				minOccurs="1" />
		</sequence>
	</complexType>

	<complexType name="Policies">
		<sequence>
			<element name="value" type="string" maxOccurs="unbounded" minOccurs="0"/>
		</sequence>
	</complexType>
</schema>

=== rakeshkanchalwar/TestingMirror/com.bitwise.app.common/src/resources/ComponentConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Config xmlns:tns="http://www.bitwise.com/ComponentConfig" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.bitwise.com/ComponentConfig ComponentConfig.xsd ">
  <tns:component>
    <tns:name>tns:name</tns:name>
    <tns:category>IO</tns:category>
    <tns:defaultNamePrefix>tns:defaultNamePrefix</tns:defaultNamePrefix>
    <tns:iconPath>tns:iconPath</tns:iconPath>
    <tns:inputPort>
      <tns:numberOfPorts>0</tns:numberOfPorts>
    </tns:inputPort>
    <tns:outputPort>
      <tns:numberOfPorts>0</tns:numberOfPorts>
    </tns:outputPort>
    <tns:property>
      <tns:type>CONFIG</tns:type>
      <tns:renderer>FILE</tns:renderer>
      <tns:name>tns:name</tns:name>
      <tns:value>tns:value</tns:value>
      <tns:validation>
        <tns:expression>tns:expression</tns:expression>
        <tns:message>tns:message</tns:message>
      </tns:validation>
    </tns:property>
    <tns:properties>
      <tns:property>
        <tns:type>CONFIG</tns:type>
        <tns:renderer>FILE</tns:renderer>
        <tns:name>tns:name</tns:name>
        <tns:value>tns:value</tns:value>
        <tns:validation>
          <tns:expression>tns:expression</tns:expression>
          <tns:message>tns:message</tns:message>
        </tns:validation>
      </tns:property>
      <tns:properties/>
    </tns:properties>
    <tns:policy>
      <tns:name>tns:name</tns:name>
      <tns:value>tns:value</tns:value>
    </tns:policy>
  </tns:component>
</tns:Config>
